FROM opensuse/tumbleweed:latest
RUN zypper refresh  
RUN zypper --non-interactive install \
    erlang \
    zellij \
    helix \
    helix-runtime \
    helix-bash-completion \
    git \
    wget \
    tar
